name: vtnet_components
description: Package for all vtnet component
version: 0.0.1
homepage: https://www.ro-fe.com

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: ^5.9.0
  flutter_svg: 2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  flutter_gen_runner:

flutter:
  plugin:
    platforms:
      ios: true
      android:

  uses-material-design: true
  assets:
    - lib/assets/icons/
    - lib/assets/

flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true